name: Update Data Daily

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd api
          npm install

      - name: Build application
        run: |
          cd api
          npm run build

      - name: Start Node.js application
        run: |
          cd api
          npm run start &
          sleep 10  # Wait for the server to start

      - name: Fetch data from API
        run: |
          curl -X GET "http://localhost:3001/api/getnodewatchdata?fetch=true" -o data.json

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          rm -f data.json
          git add *
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update nodewatch data" && git push https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }})
